//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_levanluong_64131236.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTraHang
    {
        public int MaTraHang { get; set; }
        public string MaHH { get; set; }
        public int SoLuongTra { get; set; }
        public string LyDoTraChiTiet { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual TraHang TraHang { get; set; }
    }
}
