//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_levanluong_64131236.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaSanPham
    {
        public int MaDanhGia { get; set; }
        public int MaDH { get; set; }
        public string MaHH { get; set; }
        public int SoSao { get; set; }
        public string NoiDungDanhGia { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
    
        public virtual ChiTietDonHang ChiTietDonHang { get; set; }
        public virtual DonHang DonHang { get; set; }
        public virtual HangHoa HangHoa { get; set; }
    }
}
