//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_levanluong_64131236.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.AnhGiaoHangs = new HashSet<AnhGiaoHang>();
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.ThoiGianCapNhatDonHangs = new HashSet<ThoiGianCapNhatDonHang>();
            this.TraHangs = new HashSet<TraHang>();
            this.DanhGiaSanPhams = new HashSet<DanhGiaSanPham>();
        }
    
        public int MaDH { get; set; }
        public System.DateTime NgayDat { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public string MaGiamGia { get; set; }
        public decimal TongTien { get; set; }
        public string TrangThai { get; set; }
        public string MaKH { get; set; }
        public string TrangThaiGiaoHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhGiaoHang> AnhGiaoHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual KhachHang KhachHang1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThoiGianCapNhatDonHang> ThoiGianCapNhatDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraHang> TraHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaSanPham> DanhGiaSanPhams { get; set; }
    }
}
