//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_levanluong_64131236.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class webbanhang64131236Entities1 : DbContext
    {
        public webbanhang64131236Entities1()
            : base("name=webbanhang64131236Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnhGiaoHang> AnhGiaoHangs { get; set; }
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<ChiTietGioHang> ChiTietGioHangs { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<GioHang> GioHangs { get; set; }
        public virtual DbSet<HangHoa> HangHoas { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiHang> LoaiHangs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<QuanTri> QuanTris { get; set; }
    
        public virtual int HangHoa_TimKiem(string maHH, string maLH, string tenHH, Nullable<decimal> giaBanMin, Nullable<decimal> giaBanMax, Nullable<int> soThang, Nullable<int> soLuongMin, Nullable<int> soLuongMax, Nullable<int> sapHetHang, Nullable<System.DateTime> ngayNSXTu, Nullable<System.DateTime> ngayNSXDen, Nullable<System.DateTime> ngayHSDTu, Nullable<System.DateTime> ngayHSDDen, Nullable<int> sapHetHan, Nullable<bool> coHinhAnh)
        {
            var maHHParameter = maHH != null ?
                new ObjectParameter("MaHH", maHH) :
                new ObjectParameter("MaHH", typeof(string));
    
            var maLHParameter = maLH != null ?
                new ObjectParameter("MaLH", maLH) :
                new ObjectParameter("MaLH", typeof(string));
    
            var tenHHParameter = tenHH != null ?
                new ObjectParameter("TenHH", tenHH) :
                new ObjectParameter("TenHH", typeof(string));
    
            var giaBanMinParameter = giaBanMin.HasValue ?
                new ObjectParameter("GiaBanMin", giaBanMin) :
                new ObjectParameter("GiaBanMin", typeof(decimal));
    
            var giaBanMaxParameter = giaBanMax.HasValue ?
                new ObjectParameter("GiaBanMax", giaBanMax) :
                new ObjectParameter("GiaBanMax", typeof(decimal));
    
            var soThangParameter = soThang.HasValue ?
                new ObjectParameter("SoThang", soThang) :
                new ObjectParameter("SoThang", typeof(int));
    
            var soLuongMinParameter = soLuongMin.HasValue ?
                new ObjectParameter("SoLuongMin", soLuongMin) :
                new ObjectParameter("SoLuongMin", typeof(int));
    
            var soLuongMaxParameter = soLuongMax.HasValue ?
                new ObjectParameter("SoLuongMax", soLuongMax) :
                new ObjectParameter("SoLuongMax", typeof(int));
    
            var sapHetHangParameter = sapHetHang.HasValue ?
                new ObjectParameter("SapHetHang", sapHetHang) :
                new ObjectParameter("SapHetHang", typeof(int));
    
            var ngayNSXTuParameter = ngayNSXTu.HasValue ?
                new ObjectParameter("NgayNSXTu", ngayNSXTu) :
                new ObjectParameter("NgayNSXTu", typeof(System.DateTime));
    
            var ngayNSXDenParameter = ngayNSXDen.HasValue ?
                new ObjectParameter("NgayNSXDen", ngayNSXDen) :
                new ObjectParameter("NgayNSXDen", typeof(System.DateTime));
    
            var ngayHSDTuParameter = ngayHSDTu.HasValue ?
                new ObjectParameter("NgayHSDTu", ngayHSDTu) :
                new ObjectParameter("NgayHSDTu", typeof(System.DateTime));
    
            var ngayHSDDenParameter = ngayHSDDen.HasValue ?
                new ObjectParameter("NgayHSDDen", ngayHSDDen) :
                new ObjectParameter("NgayHSDDen", typeof(System.DateTime));
    
            var sapHetHanParameter = sapHetHan.HasValue ?
                new ObjectParameter("SapHetHan", sapHetHan) :
                new ObjectParameter("SapHetHan", typeof(int));
    
            var coHinhAnhParameter = coHinhAnh.HasValue ?
                new ObjectParameter("CoHinhAnh", coHinhAnh) :
                new ObjectParameter("CoHinhAnh", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HangHoa_TimKiem", maHHParameter, maLHParameter, tenHHParameter, giaBanMinParameter, giaBanMaxParameter, soThangParameter, soLuongMinParameter, soLuongMaxParameter, sapHetHangParameter, ngayNSXTuParameter, ngayNSXDenParameter, ngayHSDTuParameter, ngayHSDDenParameter, sapHetHanParameter, coHinhAnhParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_HuyDonHang(Nullable<int> maDH)
        {
            var maDHParameter = maDH.HasValue ?
                new ObjectParameter("MaDH", maDH) :
                new ObjectParameter("MaDH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HuyDonHang", maDHParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_ThongKeDoanhThu_Result> sp_ThongKeDoanhThu(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string loaiThongKe)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var loaiThongKeParameter = loaiThongKe != null ?
                new ObjectParameter("LoaiThongKe", loaiThongKe) :
                new ObjectParameter("LoaiThongKe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeDoanhThu_Result>("sp_ThongKeDoanhThu", tuNgayParameter, denNgayParameter, loaiThongKeParameter);
        }
    
        public virtual ObjectResult<sp_ThongKeDoanhThuTheoLoaiHang_Result> sp_ThongKeDoanhThuTheoLoaiHang(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeDoanhThuTheoLoaiHang_Result>("sp_ThongKeDoanhThuTheoLoaiHang", tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<sp_ThongKeDoanhThuTheoSanPham_Result> sp_ThongKeDoanhThuTheoSanPham(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeDoanhThuTheoSanPham_Result>("sp_ThongKeDoanhThuTheoSanPham", tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<sp_TopSanPhamBanChay_Result> sp_TopSanPhamBanChay(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, Nullable<int> topN)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TopSanPhamBanChay_Result>("sp_TopSanPhamBanChay", tuNgayParameter, denNgayParameter, topNParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<ThemVaoGioHang_Result> ThemVaoGioHang(string maKH, string maHH, Nullable<int> soLuong)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var maHHParameter = maHH != null ?
                new ObjectParameter("MaHH", maHH) :
                new ObjectParameter("MaHH", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThemVaoGioHang_Result>("ThemVaoGioHang", maKHParameter, maHHParameter, soLuongParameter);
        }
    
        public virtual int XacNhanNhanHang(Nullable<int> maDH, string maKH)
        {
            var maDHParameter = maDH.HasValue ?
                new ObjectParameter("MaDH", maDH) :
                new ObjectParameter("MaDH", typeof(int));
    
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XacNhanNhanHang", maDHParameter, maKHParameter);
        }
    
        public virtual int XuLyDonHang(Nullable<int> maDH, string trangThai, string trangThaiGiaoHang, string maNV, string duongDanAnh)
        {
            var maDHParameter = maDH.HasValue ?
                new ObjectParameter("MaDH", maDH) :
                new ObjectParameter("MaDH", typeof(int));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            var trangThaiGiaoHangParameter = trangThaiGiaoHang != null ?
                new ObjectParameter("TrangThaiGiaoHang", trangThaiGiaoHang) :
                new ObjectParameter("TrangThaiGiaoHang", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var duongDanAnhParameter = duongDanAnh != null ?
                new ObjectParameter("DuongDanAnh", duongDanAnh) :
                new ObjectParameter("DuongDanAnh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XuLyDonHang", maDHParameter, trangThaiParameter, trangThaiGiaoHangParameter, maNVParameter, duongDanAnhParameter);
        }
    }
}
