//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_levanluong_64131236.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public string MaNV { get; set; }
        public string username { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public System.DateTime NgayLamViec { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
    
        public virtual QuanTri QuanTri { get; set; }
    }
}
