//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_levanluong_64131236.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TraHang()
        {
            this.AnhTraHangs = new HashSet<AnhTraHang>();
            this.ChiTietTraHangs = new HashSet<ChiTietTraHang>();
        }
    
        public int MaTraHang { get; set; }
        public int MaDH { get; set; }
        public Nullable<System.DateTime> NgayTraHang { get; set; }
        public string LyDoTraHang { get; set; }
        public string NoiDungTraHang { get; set; }
        public string TrangThaiTraHang { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhTraHang> AnhTraHangs { get; set; }
        public virtual DonHang DonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTraHang> ChiTietTraHangs { get; set; }
    }
}
